version: '1'

services:
  tensfer-backend:
    command: yarn
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
    env_file:
      - .env
    ports:
      - '9000:9000'
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
