import config from '@config/index';
import nodemailer from 'nodemailer';
import nodemailMailgun from 'nodemailer-mailgun-transport';

/**
 * @description contains utility function to send emails
 * THIS CODE IS TO BE REVIEWED
 */
class SendEmail {
  /**
   * @param {string} email - email address to send the message to
   * @param {string} first_name - User's first name
   * @param {string} token - Token generated during signup
   * @returns {boolean} specifies if the email was sent successfully
   */
  static verifyEmail({
    email,
    first_name,
    token
  }: {
    email: string;
    first_name: string;
    token: string;
  }) {
    const details = {
      email,
      subject: 'Welcome to Tensfer!',
      html: `'<div style="width: 90%; margin: 5em auto;
       box-shadow: 0 0 10px rgba(0,0,0,.9);">
        <div>
          <div>
            <div style="background-color: #2084ba; height: 3rem; width: 100%">
                <h2 style="text-align: center; color: white;
                 padding-top: 10px;">Tensfer</h2>
            </div>
            <h4 style="text-align: center">Hi! ${first_name}</h4>
          </div>
          <div style=" padding: 0px 20px 20px 20px">
            <div>
              <p>Please verify that your email is <strong>${email}</strong>
               when you signed up.</p>
              <p>Click on the button below to verify.</p>
              <button style="color: white; background-color: #2084ba;
               border: none; border-radius: 10px; text-align: center;
                padding: 10px;">
                <a  href="${config.MAIL_GUN_API_KEY}/auth/verify_email?token=${token}"
                 style="text-decoration: none;
                 color: white;">Verify Account</a></button>
            </div>
            <div>
              <h3 style="text-align: center">Thank you</h3>
              <h3 style="text-align: center">
              Please do not reply, this is an autogenerated email.</h3>
            </div>
          </div>
        </div>
      </div>`
    };

    return SendEmail.emailSender(details);
  }

  /**
   * This function sends an email on verification of email address
   * @param {string} email - email address to send the message to
   * @param {string} token - Token generated during signup
   * @returns {boolean} specifies if a verification email was sent to user
   * after registration
   */
  static confirmRegistrationComplete(email: any) {
    const details = {
      email,
      subject: 'Email Verification - Tensfer',
      html: `<p>Your registration has been completed<p>
      <p>Thank you for registering with Tensfer.</p>
       <p> >>>
       <a href=${config.MAIL_GUN_API_KEY}/home> Go to your profile </a> <<< </p>`
    };
    return SendEmail.emailSender(details);
  }

  /**
   * This function sends an email to reset password
   * @param {string} email - email address to send the message to
   * @returns {boolean} specifies if a verification email was sent to user
   * after registration
   */
  static resetPassword(email: any) {
    const details = {
      email,
      subject: 'Reset Password - Tensfer',
      html: `<div>
        <p>Click on the button below to reset your password.</p>
        <button style="color: white; background-color: #2084ba;
        border: none; border-radius: 10px; text-align: center;
        padding: 10px;">
        <a  href="${config.MAIL_GUN_API_KEY}"
          style="text-decoration: none; color: white;">
        Reset Password</a></button>
        </div>`
    };
    return SendEmail.emailSender(details);
  }

  /**
   *
   * @param {object} details - Object containing info for sending email
   * @returns {boolean} sends email to users
   */
  static async emailSender(details: { email?: any; subject: any; html: any; }) {
    const auth = {
      auth: {
        api_key: config.MAIL_GUN_API_KEY,
        domain: config.MAIL_GUN_DOMAIN
      }
    };
    const transporter = nodemailer.createTransport(nodemailMailgun(auth));
    const msg = {
      from: '<me@beveloper.com>',
      html: details.html,
      subject: details.subject,
      to: 'bkrofegha@gmail.com'
    };
    try {
      const isEmailSent = await transporter.sendMail(msg);
      if (isEmailSent) {
        console.log('mail sent');
        return true;
      } else {
        console.log('Email not sent');
        return false;
      }
    } catch (error) {
      console.log('mail not sent!');
      return false;
    }
  }
}
export default SendEmail;
